name: bspyalgo
dependencies:
   - python=3.6
   - ipython
   - pip
   - pip:
     - pyjson
     - git+https://github.com/BraiNEdarwin/brainspy-instruments.git
     - git+https://github.com/BraiNEdarwin/brainspy-processors.git
